access-control:
  end-points:
    - url-pattern: /sample
      rights:
        - apiAccessible
    - url-pattern: /{sampleName}
      path-variable: hehe
      rights:
        - apiAccessible
        - showSampleName
